CREATE DATABASE MYBATIS;
USE MYBATIS;
CREATE TABLE USERS(ID INT PRIMARY KEY AUTO_INCREMENT, NAME VARCHAR(20), SEX VARCHAR(20), AGE INT);
INSERT INTO USERS(NAME,SEX, AGE) VALUES('张三丰', '男' ,27);
INSERT INTO USERS(NAME,SEX, AGE) VALUES('梅长苏', '男', 27);
INSERT INTO USERS(NAME,SEX, AGE) VALUES('鲁智深', '男', 30);